const constants = {
  FETCH_USERS_SUCCESS: "FETCH_USER_SUCCESS",
  ADD_USER: "ADD_USER",
  UPDATE_USER: "UPDATE_USER",
  START_ADDING_USER: "START_ADDING_USER",
  STOP_ADDING_USER: "STOP_ADDING_USER",
  DELETE_USER: "DELETE_USER",
  CHANGE_USER: "CHANGE_USER",
  SET_ROW_EDITING: "SET_ROW_EDITING"
};

export default constants;
